"""last name unique fix

Revision ID: a7a521aa0a87
Revises: 3ba66f39986f
Create Date: 2020-09-14 21:59:48.318132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a521aa0a87'
down_revision = '3ba66f39986f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_index('ix_user_lastname', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=1)
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=1)
    # ### end Alembic commands ###
